config/routes.rb
GleeRequests::Application.routes.draw do
  resources :requests, :only => [:index, :create, :destroy]

  get "pages/home"

  root :to => "requests#index"

end

app/models/request.rb
class Request
  include Mongoid::Document
  include Mongoid::Timestamps
  field :track, :type => String
  field :artist, :type => String
  field :points, :type => Integer
  
  validates :track, :artist, :points, :presence => true
  validates :track, :uniqueness => {:scope => :artist}

  scope :top_ten, all.desc(:points).limit(10)
  
  def points_assigned
    points_assigned = Request.only(:points).where(:track => self.track, :artist => self.artist).first || {:points => 0}
    points_assigned[:points]
  end
  
  def total_points
    points_assigned
  end
  
  def read_request
    Request.where(:track => self.track, :artist => self.artist).first
  end
  
  def save_or_update(params)
    self.track = params[:track]
    self.artist = params[:artist]
    current_request = read_request
    
    if current_request
      current_request.points +=1
      current_request.save
    else
      self.points = 1
      self.save
    end
  end
  
  def subtract_point
    if self.points == 1
      self.destroy
    else
      self.points -= 1
      self.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
require 'lastfm'

class PagesController < ApplicationController
  def home
    unless params[:song].blank?
      @search_results = search_results(params[:song],params[:artist])
    end
  end

  protected
  def search_results(song,artist)
    lastfm = Lastfm.new('0106743c51b1b22f792a3359ac47c413', 
                        '0cee1e0928f0183d5ae4d293dbcb7d6b')
    
    token = lastfm.auth.get_token

    track_search = lastfm.track.search(song, artist, 10)

    search_results = []
    track_search['results']['trackmatches']['track'].each do |track|
      image_uri = ""
      unless track['image'].nil?
        track['image'].each do |image| 
          image_uri = image['content'] if image['size'] == 'small'
        end
      end
      search_results << {:track => track['name'], :artist => track['artist'], :image => image_uri }
    end
    search_results
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.xml
  def index
    @requests = Request.top_ten
    
    unless params[:song].blank?
      @search_results = search_results(params[:song],params[:artist])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @requests }
    end
  end

  # POST /requests
  # POST /requests.xml
  def create
    #@request = Request.new(params[:request])
    @request = Request.new

    respond_to do |format|
      if @request.save_or_update(params)
        format.html { redirect_to requests_path }
        format.xml  { render :xml => @request, :status => :created, :location => @request }
      else
        format.html { redirect_to requests_path }
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.xml
  def destroy
    @request = Request.find(params[:id])
    #@request.destroy
    @request.subtract_point

    respond_to do |format|
      format.html { redirect_to(requests_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  def search_results(song,artist)
    lastfm = Lastfm.new('0106743c51b1b22f792a3359ac47c413', 
                        '0cee1e0928f0183d5ae4d293dbcb7d6b')
    
    token = lastfm.auth.get_token

    track_search = lastfm.track.search(song, artist, 10)

    search_results = []
    track_search['results']['trackmatches']['track'].each do |track|
      image_uri = ""
      unless track['image'].nil?
        track['image'].each do |image| 
          image_uri = image['content'] if image['size'] == 'small'
        end
      end
      search_results << {:track => track['name'], :artist => track['artist'], :image => image_uri }
    end
    search_results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
  def points_for(track,artist)
    request = Request.new
    request.track = track
    request.artist = artist
    return request.total_points
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = csrf_meta_tag
    /[if lt IE 9]
      = javascript_include_tag 'html5'
    = stylesheet_link_tag 'compiled/grid.css'
    = stylesheet_link_tag 'compiled/text.css'
    %title Glee Requests
  %body.container_12
    - if flash.notice
      .notice= flash.notice
    - if flash.alert
      .alert= flash.alert
    = yield
    = javascript_include_tag :defaults

app/views/pages/_search_result.html.haml
%li
	%ul
		%li
			%div.points=points_for(search_result[:track], search_result[:artist])
			=link_to "Cheer!", requests_path(search_result), :class => 'cheer-link', :method => 'post'
		%li
			%div.song-name
				=search_result[:track]
				%span
					=" by #{search_result[:artist]}"
		%li.image=image_tag(search_result[:image]) unless search_result[:image].blank?

app/views/pages/home.html.haml
%h1.grid_12
	=link_to "Song Search", root_path
	
%div.grid_4
	%p Which song would you like to suggest?
	
	=form_tag "/", :method => :get, :id => 'search-form' do
		%h1 Search
		%fieldset
			=label_tag :song
			=text_field_tag :song, params[:song], :options => 'autofocus'
		%fieldset
			=label_tag :artist
			=text_field_tag :artist, params[:artist]
		%fieldset
			=submit_tag "Search", :name => nil

%div#search-results.grid_8	
	=render :partial => "search_result", :collection => @search_results

app/views/requests/_form.html.haml
= form_for @request do |f|
  -if @request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@request.errors.count, "error")} prohibited this request from being saved:"
      %ul
        - @request.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :track
    = f.text_field :track
  .field
    = f.label :artist
    = f.text_field :artist
  .field
    = f.label :points
    = f.text_field :points
  .actions
    = f.submit 'Save'

app/views/requests/edit.html.haml
%h1 Editing request

= render 'form'

= link_to 'Show', @request
\|
= link_to 'Back', requests_path

app/views/requests/index.html.haml
%h1 Top 10 Requests

%div.grid_6
  %table#top-10
    %tr
      %th.position
      %th Track
      %th Artist
      %th Cheers
      %th
      %th

    - @requests.each_with_index do |request, index|
      %tr
        %td.position= index+1
        %td= request.track
        %td= request.artist
        %td.position= request.points
        %td=link_to "Cheer!", requests_path({:track => request.track,:artist => request.artist}), :class => 'cheer-link', :method => 'post'
        %td= link_to 'Slush!', request, :confirm => 'Are you sure?', :class => 'slush-link', :method => :delete

%hr

%h1.grid_12
  =link_to "Song Search", root_path
	
%div.grid_4
  %p Which song would you like to suggest?
	
  =form_tag "/", :method => :get, :id => 'search-form' do
    %h1 Search
    %fieldset
    =label_tag :song
    =text_field_tag :song, params[:song], :options => 'autofocus'
    %fieldset
      =label_tag :artist
      =text_field_tag :artist, params[:artist]
    %fieldset
      =submit_tag "Search", :name => nil

%div#search-results.grid_7
  %ul
    =render :partial => "pages/search_result", :collection => @search_results

app/views/requests/new.html.haml
%h1 New request

= render 'form'

= link_to 'Back', requests_path

app/views/requests/show.html.haml
%p#notice= notice

%p
  %b Track:
  = @request.track
%p
  %b Artist:
  = @request.artist
%p
  %b Points:
  = @request.points

= link_to 'Edit', edit_request_path(@request)
\|
= link_to 'Back', requests_path